2025/07/10 CI CD 작업을 위한 커밋

diff --git a/toss-pay-frontend/Dockerfile b/toss-pay-frontend/Dockerfile
--- a/toss-pay-frontend/Dockerfile
+++ b/toss-pay-frontend/Dockerfile
@@ -3,7 +3,7 @@ FROM node:18-alpine as builder
 WORKDIR /app
 COPY . .
 RUN yarn install
-RUN yarn build
+RUN yarn build || (echo "🛑 Build failed!" && cat /app/.next/trace | true && exit 1)
 RUN yarn export
 
 FROM nginx:alpine
